[binaries]
deps = ["out/make/deb/x64/elbajel_0.0.1_amd64.deb",]

[install]
deps=["/usr/bin/elbajel"]

[start]
exec = "electron ."

["out/make/deb/x64/elbajel_0.0.1_amd64.deb"]
deps = ["main.js", "window.js"]
exec = "electron-forge make"

["/usr/bin/elbajel"]
deps=["out/make/deb/x64/elbajel_0.0.1_amd64.deb"]
exec = "sudo dpkg -i $<"

[remove]
exec="sudo apt-get remove elbajel"